language: go
go:
- 1.8
script: 
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=isaiahsolo/trackhours.co
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- docker build -f server/Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
env:
  global:
  - secure: ItX1binWZ0k97W45aE3mjQl64tT7kawnSJMmy3BKqaaoSGOnTjPluNYpYq0OTQODTicZ2/Y4xhTbcPAq6IS6Y+tYYtP9SuCDbF8rK4xGDFmgDQIl3N55Nkc5lKkAUrgdXqgQC9qJcjqSd4BSncN9upyBk+Vy4hJZ6HgQqIvXq2hvYhnBkgkat66YxueCnsqb9Sw81NjPjy6RcDKGb+XIj1ixA5JW9OyonVyuSYPEJ1zTsmNKFu8XPHlX11BOckROMmgv6NXx6D+kkU576Bp6+OSQx984V8CdU5a6HzqkQLNghK4Md4piZRnIgWIdPMnyv1Wqmk0JZVjQBMxPg+d5gJdfSYWze5f+BfhD9bjBhFPuDqP522pFMdTtziUFJ6LYlvvTRCa7UBob4FFJhE/ZgL4dddYHFIgF9qXig77xi6kmDBjv31xhTXQbmUm0PQ8aJTgK2goW/tUwp7jMT0xvJS20taC8G/gfcKOnjITWpx4Mymu77IuAhlyllxEZf6ndv1FxNVB0u9KqR5A/aOnAZXqw/uNZs4vrN5HPRTDmxNf4vcwGaUGRGnC/4+p6HIeOZfGHena4w7VR9A0Q9xeL9PZ0Z8sbhDoqKiNPU9qOzc5rjqD4NbOpchdtMwQgbCqtt73VaR+7VV+RlCbce8QsO+mjVrNdCHiix9cokMdl7Gs=
  - secure: d9dqeGLI41szVbkXPEq68vXH7YyjuRkousS9MKf2EnwxiT4daH99PnkoJAoL9ngTlere2u+NU9HyhZE4e+lzwh2lmaFqVVxXzWcyYrcYGOpXNLSUT56E1ArPw25qxrQEp3XsP923vS6ezoX6ZRZOOUHQnWtZJ1l0QqQxQMxlLQp+mRn9X80KK/GIGPbMEseOec0WNPYTl7O0bXVbaJLgKbiHnSCGPfT7sh6gmqLIE2du4SZJ0BCDZ5hmsSoXkU8F84egHG9hGic335yGP9u1xa8M1M71qnSiZTW7Bkql28mz53Z93UjJyz0Qnun+6pA1Ne7t/OJtERtXO6DGLputgcVdR4Zq2OGk7XkTLzOVQP15IB8MIruaTYlz1uB0sH9ZzanEzuR35maxP4o5Zec5c8AVxyDkmHHlhFsciIKfi+qecLW6KsMpcIXQoyRes3gM5+c64QZBiSjq8NLrXjjB02tx7vV3A9HAr75pjDzJz1TuuvgNTfmocqJbgzBc8Y4y3IV7JiwzsptDj56sOW/j+tvhshcfij2g6mn4cC6meSaHcd4EkoXzfc88T9+/sm9PbFCwMqVKCAEMQYkLxQqVwZhE2YsKA0cXCTB/nclsdv9N2CeRzjzMFmSV1HTgIzhW1xVm+Svvlcbn5WU2dvDWbyQAaPTDHN4oOond1d/CJb8=
