language: go
go:
- 1.12
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: uCEAztymk1COeCyjybRhFzcq0he38Dc1zL0c8+sGBNXPv+Ht/wS+xpjqlqLjNfvD46whtVMN/Gao4hgTVY1MTfp/RLebnRuESm/74xAJ486VsQ15A4rmv6o6O+LGQVv3Znf5FfDBtI5l383GPTKv6x2HhnyDccTnvsYsWRC2dahobNHrQuEZ0qGSQTVH+ivT8MMTtAz/ieeGZ+7qxjwaqwETJg0ExRXIUmg9Se6kQdvsbc6DSYiz4W7OM4qUmnaq3vRbUnc1c/181bZauUREQ1SYcdqPVU11INz7XO5+vcnp4nbeVeVP356CcsChJ3tLQfqLfkjPk5vpCCwkjHUypObODKZuYEhdl2xlflUFTrbUaw6Q87aTD/PhuORLO5oWC3TsdfW2F9G+3FPxbyzQugWwwnNI/2q7Y6jLO5McM49CrKCnfZKUnxR5S3VBU8KhyBcHqJEGTEC9YN54yFZsYrcI8CDToySyNH/PpU7rf3un0OGJcB3jC8HgASGDjNpk9XSOsFHz/v/xO5FnM6TNos81G2TzICo5+kcB4SCkVjqWZeftK66CkmFJSCvi1Y0Oye1ebhhnDj2VkQfgNAY4qN394G6nfLH+g8iZGQe/14jj0dcKjY6mbeY5p+TGlit/ORpdA8xn54dVVNNSVsrZ+450SDuoFIp/QlTKq7XEFC0=
  - secure: aHsyZuIJW7lcMS6jijHwMThEZ7YM/wghCXeE8iREL8YQZaeeoub049IxiSmcd3UDKsxR0DsA+5mXm78bY1B/TQSvgqa0rqZNILIMdvQ+aiSPeGmoKNGqtwSyAe9SeN9UmPa45FxVN27fNTzQu+VmIYJSfDPRMulCgUtuPbBrJp+blTMbbsdNdDeA624VeWCd9wF4qw8qwJpjxX1uzB7Z8Vj/TU1NBevoEXMG7drunIU7Kex4VCkLHJlxWlh7/0jRtJXcb+BGL7mLBMlRtTV+k0mIFzZspmO/66gXBwEOCkkdZEHiNSF8jRhHs+qQZR4HV4G5pZmwpczJkSEQsnjZbG9dh5PxLequNdMFQYgFfM2Ftlt6LL3nb4Z4KYccj0fFCMDiGScFl9xIVDEfXpMSPUTk3t6yDIpFllXMLZoAeTV/KV6aYV7Lbzm4/PAuzGFGGYOa/Nbq+16C4NYCt/Ysz/Si7K7uvkHk6Zq//tL9zUr7FYcWw+zJyM+ShFgCYb3RF3CqMINfohPEvajbQd+akWluHe5amhu8kGwTxEkxtQIOTJwFnn34i1WvuDCm/arBNumREtIWBMNBb4Bv7K/HrsijfKVee/vikbJXKNnxKTev6ZayfNCvMYAoKwS1MIvzXtiZOyHhdtqwdbfKyVRablvpSGgUalYgd35wiyQ7qG0=
script: 
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=isaiahsolo/trackhours.co
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- docker-compose pull
- docker-compose build
- docker images
- docker-compose push
