language: go
go:
- 1.12
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: LdSuPI0aL7jlzohRApP5Vt1oJ3Ic9l+O5aadTkZ6YVS20EMRVaQwNXZl1pr+gaIm2ZkdkqL/no5gFwTjSYSy+ksF++TYY/oqOG94eYa/ESwCnmfExJ7RySP0LpYuBQ8ZmjjGWXvqk3ouarSavRb/tg6bsPWFzMLAA1qYjze9N6C8MNfVvKgpnem0GGy0q/KmXZkoLipcenWBxTfPTyYFV+SDmDY8fU9WtLywFcMnzVltVttyFmGRgz2Ge4dT6mSdw+9LXqa21uzripGLgLDZSM/8PL9e0dVxJSHaMDymmek+sOkWeWftDDOIY52XZzVXKZiqfjyoHYwsUATpqkHSotXKFxwV4n13Hha67IqYAAIZbPxRZucuPP8BElENYoskmInYQ3MGstKMUfX7TKx64LuxHkRLGD03Gp/Y1lEXcuwLglai9AdLg2YzKxuW4uXi7bkaRhhV5VJ7gIOpd79ne3pGajRRHSwUEERxQXwaO+yuTWjjxTJgPnUfzIKrxx0lQinmj9s89RvD2o4kqJLAhDVRyR0aldoWW3ZBAgxPIE/lIe5dOcvufryy3CeEyDp/maGT2Zd/vZxZnvj4zOuFG545uERAbLqnZt6crJGEA93WHuVUsgc2EY1mXYcifXY9IFketcnLostKGFYo5cXB/3nvKy1iA7oS8HNK9cU8xlI=
  - secure: KUYyGPz+R/CT2ZsrcUYgcAJgQTXOtDWqCX+zKTypA2CQJCfcqXjUF7udDO52duYGOy0GezaCQQwLGKAr2IOH1j6OJXobTY1sVSNt2Hf/wwgzW3TCPtaVaT+1cvqJsjzb/F+FdpNYOYflz7oh/ufIVNRXaCQm6GmoNPa9ooHsPJCkGmRuQWM5EcIotAhjEYMREKyZK3nnBmacR0U+9wYphffPTZ3HnsRPU6kA2Bwkpr7NxthDNwgLR+4BhKPAXg1Bs1hokETxw1m042xPd1+l/D33sBLk7umscW6AcceWmRv/sRmVDxzgfK5rKYyPjF2cBcUdY94hqEc/ifer8Ax0ls6lZWmaY24z3b+Egw7HuX/ZFTca8I4gw8kJUZfmJ1gIlPZ+A01IcJN5sBN/xhBEf3XQGm5+hIISWgljYCSzXVkkws0f8UeZtqGdPKBCsi46xwpAMlYvhS+9UjgC6uYYhhFDd0vkkRGQ7Bj9n1b5Yk7y2p8tcAmZF0xpwEAUkYb7sgX2JCoP2flg2EN4rO7n+PTpVH1Ik9vsjAD4OY+u7964mWBsVKPwH+Z20QynQIGK0a8/kTwENFkwNm4RjIuqmM6ux/0DUWuQvKvyXEHHuBHPmdtiDR7kYAMAH9Wct5ZvT1lJalObRehFOp3TzTnb0/DFtW8gfYOd1ZCWn+BMN1g=
script: 
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=isaiahsolo/trackhours
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- docker build -f server/Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
