language: go
go:
- 1.12
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: aHsyZuIJW7lcMS6jijHwMThEZ7YM/wghCXeE8iREL8YQZaeeoub049IxiSmcd3UDKsxR0DsA+5mXm78bY1B/TQSvgqa0rqZNILIMdvQ+aiSPeGmoKNGqtwSyAe9SeN9UmPa45FxVN27fNTzQu+VmIYJSfDPRMulCgUtuPbBrJp+blTMbbsdNdDeA624VeWCd9wF4qw8qwJpjxX1uzB7Z8Vj/TU1NBevoEXMG7drunIU7Kex4VCkLHJlxWlh7/0jRtJXcb+BGL7mLBMlRtTV+k0mIFzZspmO/66gXBwEOCkkdZEHiNSF8jRhHs+qQZR4HV4G5pZmwpczJkSEQsnjZbG9dh5PxLequNdMFQYgFfM2Ftlt6LL3nb4Z4KYccj0fFCMDiGScFl9xIVDEfXpMSPUTk3t6yDIpFllXMLZoAeTV/KV6aYV7Lbzm4/PAuzGFGGYOa/Nbq+16C4NYCt/Ysz/Si7K7uvkHk6Zq//tL9zUr7FYcWw+zJyM+ShFgCYb3RF3CqMINfohPEvajbQd+akWluHe5amhu8kGwTxEkxtQIOTJwFnn34i1WvuDCm/arBNumREtIWBMNBb4Bv7K/HrsijfKVee/vikbJXKNnxKTev6ZayfNCvMYAoKwS1MIvzXtiZOyHhdtqwdbfKyVRablvpSGgUalYgd35wiyQ7qG0=
  - secure: KrmlFKub5CKeABlFLFZ/LPhdisiJbSQrmhd8o7PlHYKs4/hg454ELd3vkrZ1M32Ik2QGU2i44cHVkkwRKuSfW1hqbkBEQuOG8CIDBlGJvqcQmB13BXbv00TASkryMXa36R2W4inmxk7zuW9hijd0dJJ+naLsE1uVU/NqyYol8Oh0Ae9ZHACqJLRyRIyO0fs4ep8FKncJyWzTUD0OA+9GmQNzCYB8q3S7af2g64fBg8eEFQHQu1Hkn7Aqwffz1ia7QlJngfx+KcrToNIggA++KCs5jNMJMmTK3XgjyvJQ8wC+jyspQJv9w6ppW/JRKcINydr7iVvNphYIY2smP9kFsh4oU92CqU5qOt2D4gfrFAmYhZxwgc51UW7j7/TQSBVtE+Rxcs+SLUozJWjevmG4f4MWJByOMtN4au8IvFaw3oRyJwb3Wk/T3ZEQSJHCp46rjcE4FCKlwoYefhDO0n4aygaJRCvwqYdPL5EP9OWFRLMdNVeZEIQEjKzBicylVHbdQAfEGEK8piZCq2tSZTGrWVy0mHyAIC80bj1AjwM3jmVKZRloR39YH92eULlj8KX7WS1BHiMRFGfeifzYdWohUlV2jGTz9fRH1sEaEuBga6MSy01OkNHONvM+NOoZS0CnxLNJH9ktMW+QFieNnwa9ELzkGP4QMu9gxawmGY1Z368=
script: 
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker-compose build
- docker images
- docker-compose push
