language: go
go:
- 1.12
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: bhPlXMlmAMba/AXiAaM4OgIDdCxCLmpIn2gDvRqjWvelPgfij2H0DQG2zorQL8b7oyR+xxIXacjrGjxW60f+g66etQUpF2vFTCq8quvbaYF+JRGlEV2Mkse/iJ4MJwCchzAgW7O0tyxqEUFZLfEut0lR1R9anqSEO4ltPEF+q+PAavKwygtcMPk5plhOAyoxRFCVVM9jJ2dh4Hq0pRVEOHmC7ltuxc8jWPSAI51GH2VqRfQqd+jE50GzDt1YhYcM0D6PH6wjYEW6yeEMxkJZ0fR5GEKVf6ZpbYqfI+8DZEPAk/hjtv1OfmpSvgM7/6FPNlhnkHw98p4X2JFGnJSoVNEIN77kABi4+R7DpB/h5GcbpsG4Yox5AeoRRbA4elyLl6yWI/qIf2itf+vX2ip7N13JQju6W2KfS57BHcvzWqmMINXw5AeN/fT6GSvdmHvaTaV3kkO6iTymOoWtKhPHHnmPFAz7dSRIqToyeiV+Ci1Qh+nAyiI/YhMcnjjmRv95wHjc50TA2B6n7na56ZlG+PcdYSCgK4e29obzypGE4k/QqEb1mddKjehKNLD/9Pq2m8HVAdSm1F94l6T0GY860j0+L5u1yFgfHsEz7hS6k0/bHtMxuR2TT/nMfMGjNxozGKsLgfaHBHl3ApKv1mrKbyiC+dLHKYUZ3+1T+18CYeA=
script: 
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=isaiahsolo/trackhours
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- docker build -f server/Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
