language: go
go:
- 1.12
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: uCEAztymk1COeCyjybRhFzcq0he38Dc1zL0c8+sGBNXPv+Ht/wS+xpjqlqLjNfvD46whtVMN/Gao4hgTVY1MTfp/RLebnRuESm/74xAJ486VsQ15A4rmv6o6O+LGQVv3Znf5FfDBtI5l383GPTKv6x2HhnyDccTnvsYsWRC2dahobNHrQuEZ0qGSQTVH+ivT8MMTtAz/ieeGZ+7qxjwaqwETJg0ExRXIUmg9Se6kQdvsbc6DSYiz4W7OM4qUmnaq3vRbUnc1c/181bZauUREQ1SYcdqPVU11INz7XO5+vcnp4nbeVeVP356CcsChJ3tLQfqLfkjPk5vpCCwkjHUypObODKZuYEhdl2xlflUFTrbUaw6Q87aTD/PhuORLO5oWC3TsdfW2F9G+3FPxbyzQugWwwnNI/2q7Y6jLO5McM49CrKCnfZKUnxR5S3VBU8KhyBcHqJEGTEC9YN54yFZsYrcI8CDToySyNH/PpU7rf3un0OGJcB3jC8HgASGDjNpk9XSOsFHz/v/xO5FnM6TNos81G2TzICo5+kcB4SCkVjqWZeftK66CkmFJSCvi1Y0Oye1ebhhnDj2VkQfgNAY4qN394G6nfLH+g8iZGQe/14jj0dcKjY6mbeY5p+TGlit/ORpdA8xn54dVVNNSVsrZ+450SDuoFIp/QlTKq7XEFC0=
  - secure: QUK1xNycrUpyhAPrQW5dA5rXOjA9ZVmY5S+BfaZRSi7qKP4QApN4i5bfCSWo/pOyF/ZvNkuM00GwaLdwnfPkaTmLbDzx683WcnXMULoglkxgZc1IVjEVdL8NA1FAJFBiqms8YRcKbY8YMgAnMQOsqXs1UkkfLISezQk6/N3kmNi1Rs26EhE2BnhSIjGXdS286DMMDvXCck5IZZCbDo17rRyIB9SFI98Q0hy1Tg6OTmIjn4tX/xYfVOtPUkCP/txTbCdv58TeJMr9A0XopVb6WLQb5ndUTFv+442BqWUtqaoxjtrDs15iUmmhcTNw6hLf3qAD+a18zut9WSDiEhSLMgvPf1rVEzTu52F7At9bGNG5wOBt5rrR4dvv0kBoovC9M+Y2MI3x3Do/iJNGP2NeSyxjBi/MUihwJFJ9Rmccb/a9LuwDXFFSxnU980aY9xv9X+0CH+RMk8b1seED2dZosnRkUQASi3lzX6fPB11Ivf0Si++NWz0EgelJNAr+9fj3XgcHy7y19drkKEALBG8pr+Bk9y7uKyxhFn3Tr580/ElawV6xiDJMI22oDSLOTajR2G1UF8DRP9fyXSzsnootstGbd++Kb9wSFUWBfJN6lz203lSRcPQ/5cGsNAtUWp/Z4dsnDu4NO/YEyZBQr+b77OeM0GqLzvmI0lk2n2v2TWQ=
script: 
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=isaiahsolo/trackhours
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- docker build -f server/Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
